from sqlalchemy import Column, Integer, String, Text, ForeignKey, DateTime
from datetime import datetime, timezone

from .database import Base, engine

# Create database tables if they do not already exist
Base.metadata.create_all(bind=engine)


# ============================================================
# USER
# ============================================================

class User(Base):
    __tablename__ = "users"

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    name = Column(
        String(100),
        nullable=False,
    )

    email = Column(
        String(150),
        unique=True,
        nullable=False,
        index=True,
    )

    password = Column(
        String(255),
        nullable=False,
    )


# ============================================================
# RESUME
# ============================================================

class Resume(Base):
    __tablename__ = "resumes"

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    user_id = Column(
        Integer,
        ForeignKey("users.id"),
        nullable=False,
    )

    filename = Column(
        String(255),
        nullable=False,
    )

    file_path = Column(
        String(500),
        nullable=False,
    )

    extracted_text = Column(
        Text,
        nullable=True,
    )

    # AI resume analysis stored as JSON string
    analysis = Column(
        Text,
        nullable=True,
    )


# ============================================================
# JOB DESCRIPTION
# ============================================================

class JobDescription(Base):
    __tablename__ = "job_descriptions"

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    user_id = Column(
        Integer,
        ForeignKey("users.id"),
        nullable=False,
    )

    title = Column(
        String(255),
        nullable=True,
    )

    company = Column(
        String(255),
        nullable=True,
    )

    description = Column(
        Text,
        nullable=False,
    )


# ============================================================
# INTERVIEW COACH
# ============================================================

class InterviewSession(Base):
    __tablename__ = "interview_sessions"

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    user_id = Column(
        Integer,
        ForeignKey("users.id"),
        nullable=False,
    )

    resume_id = Column(
        Integer,
        ForeignKey("resumes.id"),
        nullable=False,
    )

    job_id = Column(
        Integer,
        ForeignKey("job_descriptions.id"),
        nullable=True,
    )

    role = Column(
        String(255),
        nullable=True,
    )

    interview_type = Column(
        String(50),
        nullable=False,
    )

    difficulty = Column(
        String(50),
        nullable=False,
    )

    total_questions = Column(
        Integer,
        default=0,
    )

    score = Column(
        Integer,
        nullable=True,
    )

    created_at = Column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
    )


class InterviewQuestion(Base):
    __tablename__ = "interview_questions"

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    session_id = Column(
        Integer,
        ForeignKey("interview_sessions.id"),
        nullable=False,
    )

    question = Column(
        Text,
        nullable=False,
    )

    user_answer = Column(
        Text,
        nullable=True,
    )

    score = Column(
        Integer,
        nullable=True,
    )

    feedback = Column(
        Text,
        nullable=True,
    )

    ideal_answer = Column(
        Text,
        nullable=True,
    )

    created_at = Column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
    )


# ============================================================
# CAREER ROADMAP
# ============================================================

class Roadmap(Base):
    __tablename__ = "roadmaps"

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    user_id = Column(
        Integer,
        ForeignKey("users.id"),
        nullable=False,
    )

    resume_id = Column(
        Integer,
        ForeignKey("resumes.id"),
        nullable=False,
    )

    job_id = Column(
        Integer,
        ForeignKey("job_descriptions.id"),
        nullable=False,
    )

    # Target job/role generated by AI
    target_role = Column(
        String(255),
        nullable=True,
    )

    # Overall AI readiness score
    readiness_score = Column(
        Integer,
        default=0,
    )

    # AI-generated roadmap summary
    summary = Column(
        Text,
        nullable=True,
    )

    # AI-generated insights stored as JSON string
    insights = Column(
        Text,
        nullable=True,
    )

    # AI-generated recommendations stored as JSON string
    recommendations = Column(
        Text,
        nullable=True,
    )

    created_at = Column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
    )

    updated_at = Column(
        DateTime,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )


# ============================================================
# ROADMAP STAGE
# ============================================================

class RoadmapStage(Base):
    __tablename__ = "roadmap_stages"

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    roadmap_id = Column(
        Integer,
        ForeignKey("roadmaps.id"),
        nullable=False,
    )

    title = Column(
        String(255),
        nullable=False,
    )

    # completed / current / upcoming
    status = Column(
        String(50),
        nullable=False,
        default="upcoming",
    )

    duration_days = Column(
        Integer,
        default=7,
    )

    # Percentage from 0 to 100
    completion = Column(
        Integer,
        default=0,
    )

    # Controls stage ordering
    stage_order = Column(
        Integer,
        default=1,
    )


# ============================================================
# ROADMAP ITEM / TASK
# ============================================================

class RoadmapItem(Base):
    __tablename__ = "roadmap_items"

    id = Column(
        Integer,
        primary_key=True,
        index=True,
    )

    stage_id = Column(
        Integer,
        ForeignKey("roadmap_stages.id"),
        nullable=False,
    )

    # Task description
    label = Column(
        Text,
        nullable=False,
    )

    # 0 = incomplete, 1 = completed
    done = Column(
        Integer,
        default=0,
    )

    # Controls task ordering inside a stage
    item_order = Column(
        Integer,
        default=1,
    )